BOOTLOADER = atmel-dfu

RGBLIGHT_ENABLE  = no
AUDIO_ENABLE     = no
BOOTMAGIC_ENABLE = lite
<<<<<<< HEAD
RGB_MATRIX_ENABLE = WS2812
=======
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
>>>>>>> dontTouch/master
