name: PR Lint keyboards

on:
  pull_request:
    paths:
    - 'keyboards/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: trilom/file-changes-action@v1.2.4
      id: file_changes
      with:
        output: '\n'

    - name: Print info
      run: |
        git rev-parse --short HEAD
        echo ${{ github.event.pull_request.base.sha }}
        echo '${{ steps.file_changes.outputs.files}}'

    - name: Run qmk lint
      shell: 'bash {0}'
      run: |
        QMK_CHANGES=$(echo -e '${{ steps.file_changes.outputs.files}}')
        QMK_KEYBOARDS=$(qmk list-keyboards)

        exit_code=0
        for KB in $QMK_KEYBOARDS; do
          KEYBOARD_CHANGES=$(echo "$QMK_CHANGES" | grep -E '^(keyboards/'${KB}'/)')
          if [[ -z "$KEYBOARD_CHANGES" ]]; then
            # skip as no changes for this keyboard
            continue
          fi

          KEYMAP_ONLY=$(echo "$KEYBOARD_CHANGES" | grep -cv /keymaps/)
          if [[ $KEYMAP_ONLY -gt 0 ]]; then
            echo "linting ${KB}"

<<<<<<< HEAD:.github/workflows/lint.yml
<<<<<<< HEAD
            qmk lint --keyboard ${KB} && qmk info -l --keyboard ${KB}
            exit_code=$(($exit_code + $?))
=======
<<<<<<< HEAD:.github/workflows/info.yml
            # TODO: info info always returns 0 - right now the only way to know failure is to inspect log lines
            qmk info -l -kb ${KB} 2>&1 | tee /tmp/$$
            !(grep -cq ☒ /tmp/$$)
            : $((exit_code = $exit_code + $?))
=======
            qmk lint --keyboard ${KB} && qmk info -l --keyboard ${KB}
            exit_code=$(($exit_code + $?))
>>>>>>> acdcc622028a7c8e6ec086a5da2bff67fd137445:.github/workflows/lint.yml
>>>>>>> UpdateQMK
=======
            qmk lint --keyboard ${KB} && qmk info -l --keyboard ${KB}
            exit_code=$(($exit_code + $?))
>>>>>>> acdcc622028a7c8e6ec086a5da2bff67fd137445:.github/workflows/info.yml
          fi
        done
        if [[ $exit_code -gt 255 ]]; then
            exit 255
        fi
        exit $exit_code
